allow-lan: true
dns:
  default-nameserver:
  - 114.114.114.114
  - 223.5.5.5
  - 8.8.8.8
  enable: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - https://doh.pub/dns-query
listeners:
- listen: 127.0.0.1
  name: http-0
  port: 32001
  proxy: 日本 01
  type: http
  users: []
- listen: 127.0.0.1
  name: http-1
  port: 32002
  proxy: 原生地址-80-WS 01
  type: http
  users: []
- listen: 127.0.0.1
  name: http-2
  port: 32003
  proxy: 美国 01 | 专线 01
  type: http
  users: []
- listen: 127.0.0.1
  name: http-3
  port: 32004
  proxy: 原生地址-443-WS-TLS 01
  type: http
  users: []
log-level: error
mixed-port: 7890
mode: global
proxies:
- client-fingerprint: chrome
  name: 日本 01
  network: ws
  port: 443
  server: cf.zhetengsha.eu.org
  servername: v2rayserverfreenet.akyjglwiu.workers.dev
  tls: true
  type: vless
  udp: true
  uuid: 216e26c7-1f49-43a4-a860-b9517a03c69d
  ws-opts:
    headers:
      Host: v2rayserverfreenet.akyjglwiu.workers.dev
    path: /?ed=2048
- name: 原生地址-80-WS 01
  network: ws
  port: 80
  server: v2rayserverfreenet.akyjglwiu.workers.dev
  tls: false
  type: vless
  udp: true
  uuid: 216e26c7-1f49-43a4-a860-b9517a03c69d
  ws-opts:
    headers:
      Host: v2rayserverfreenet.akyjglwiu.workers.dev
    path: /?ed=2048
- name: 美国 01 | 专线 01
  password: 35e2adb8-5456-4da4-8620-bdab5132f764
  port: 443
  server: us1.4af5e705-990e-1126-6e7f-03ac1670542e.36a8c922.the-best-airport.com
  skip-cert-verify: true
  sni: new.download.the-best-airport.com
  type: trojan
  udp: true
- client-fingerprint: chrome
  name: 原生地址-443-WS-TLS 01
  network: ws
  port: 443
  server: v2rayserverfreenet.akyjglwiu.workers.dev
  servername: v2rayserverfreenet.akyjglwiu.workers.dev
  tls: true
  type: vless
  udp: true
  uuid: 216e26c7-1f49-43a4-a860-b9517a03c69d
  ws-opts:
    headers:
      Host: v2rayserverfreenet.akyjglwiu.workers.dev
    path: /?ed=2048
